### ISSUE TITLE
Klipper folder

### ISSUE THREAD

**Issue by mtcmapbell1** [CrealityOfficial/Creality_Sonic_Pad#1]
There is no klipper folder in the root directory after the "git clone" command.  There is a klipper folder in the creality folder, but it's empty.

**Comment by wildwood-code** [comment]
I am having the same issue. The klipper folder is empty.

**Comment by CrealityTech** [comment]
> There is no klipper folder in the root directory after the "git clone" command. There is a klipper folder in the creality folder, but it's empty.

we have upgrade the branch please pull it again;
thank's

**Comment by criss623** [comment]
Still empty Klipper folder

**Comment by CrealityTech** [comment]
> Still empty Klipper folder

you can git form this address https://github.com/CrealityTech/klipper-1
