### ISSUE TITLE
kernel source missing

### ISSUE THREAD

**Issue by chealy** [CrealityOfficial/Creality_Sonic_Pad#15]
I don't see where the Linux kernel source is for this device.  This should be accessible so the device can comply with the GPL.

**Comment by svobodnik** [comment]
telling us how their magic SoC works would, like, totally ruin their 3d printer business, man

**Comment by 0xD34D** [comment]
> telling us how their magic SoC works would, like, totally ruin their 3d printer business, man

Selling this as "open source" and leaving out the source to one of the biggest GPL licenced projects is a misleading business practice.

**Comment by chealy** [comment]
@Creality-Ralf 
It's been several months now since this issue was opened.  Please provide an ETA for when Crealty will address this lack of opensource support.

**Comment by chealy** [comment]
Thanks for sharing the link.  Please correct me if my understanding is wrong, but it appears that the Sonic Pad uses an Allwinner R818 SoC running the 4.9 Linux kernel.  Can you confirm what I'm seeing in the code drop and that this is what the Sonic Pad uses?
