### ISSUE TITLE
Thumbnail layer ?

### ISSUE THREAD

**Issue by chuckxxxl** [CrealityOfficial/Creality_Sonic_Pad#26]
![FB_IMG_1677099977939](https://user-images.githubusercontent.com/21015958/220759151-23e8c547-9c4a-41fc-bbf3-23094bb0df2c.jpg)

how can i set it so that the print progress is displayed in blue on the thumbnail like in the attached picture from creality?

**Comment by BakeJake** [comment]
@chuckxxxl Pretty sure it depends on the filament slicer in the firmware! (atleast my models are blue because I have it set like such in cura)

**Comment by Creality-Ralf** [comment]
You will need to slice using creality print and turn on the preview image option before slicing
