### ISSUE TITLE
BigTreeTech CR-6 board 

### ISSUE THREAD

**Issue by USL5264** [CrealityOfficial/Creality_Sonic_Pad#31]
To the developers.

I would like to request for a Bigtreetech CR-6 board config for Klipper to be added to the Sonic Pad?

This would be amazing.

Thanks

**Comment by Creality-Ralf** [comment]
Our model configuration is currently targeted at printers, and the configuration of a separate board will not be included in the fast adaptation plan for now. You may consider asking the seller of your board for the relevant information. If a motherboard is used for a particular model in high volume and we don't have the relevant quick configuration, we will give priority to adding it to our quick adaptation menu
