### ISSUE TITLE
Only a single webcam is supported

### ISSUE THREAD

**Issue by buffcode** [CrealityOfficial/Creality_Sonic_Pad#39]
I have connected two Logitech C270 to the USB ports on the back. The UI  also shows two connected cameras, but the video is always from the first camera, so you have two cameras showing the same image.

It seems, as if the `rtsp_demo` binary is always using `/dev/video0` and won't start up another process for further cameras.

Two cameras connected, Sonic Pad is showing two images (both from camera 1).

```
root@spad-5837:~# netstat -tulpn | grep rtsp
tcp        0      0 0.0.0.0:8554            0.0.0.0:*               LISTEN      5674/rtsp_demo
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      5674/rtsp_demo
tcp        0      0 0.0.0.0:8088            0.0.0.0:*               LISTEN      5674/rtsp_demo
tcp        0      0 :::8080                 :::*                    LISTEN      5674/rtsp_demo

root@spad-5837:~# lsof | grep video
5674    /usr/bin/rtsp_demo      /dev/video0

root@spad-5837:~# find /dev -type c -name 'video*'
/dev/video1
/dev/video0
/dev/dev/video1
/dev/dev/video0

root@spad-5837:~# lsusb
Bus 003 Device 003: ID 046d:0825 Logitech, Inc. Webcam C270
Bus 001 Device 007: ID 046d:0825 Logitech, Inc. Webcam C270
```

I would expect it to behave just like written in the [Mainsail docs](https://docs.mainsail.xyz/overview/settings/webcams):
![image](https://user-images.githubusercontent.com/2863518/232895871-1ef4277e-eccd-4b36-a240-8dab59192ded.png)

**Comment by Creality-Ralf** [comment]
The current system only supports the display of a video stream (for time-lapse photography / AI detection / IOT monitoring), more than 1 video stream function is temporarily in a more backward planning time
