### ISSUE TITLE
BUG: customised temp

### ISSUE THREAD

**Issue by LA3QMA** [CrealityOfficial/Creality_Sonic_Pad#5]
20.10.2022 v1.0.6.29.121

When selecting "Customised temp" it's not possible to set values higher than 220'C.

Using "Select preheat temperature" it's possible to set to i.e 250'C so this is ok.

**Comment by Creality-Ralf** [comment]
This is a bug that is fixed in the latest system as well.
Its maximum value corresponds to the "max_temp" value in printer.cfg now

**Comment by LA3QMA** [comment]
tnx
