### ISSUE TITLE
subfolders not available on the Sonic pad screen

### ISSUE THREAD

**Issue by LA3QMA** [CrealityOfficial/Creality_Sonic_Pad#6]
If you create a subfolder via the web interface it's not possible to see/select this folder from the Sonic Pad

**Comment by CrealityTech** [comment]
> If you create a subfolder via the web interface it's not possible to see/select this folder from the Sonic Pad

it's on the way

**Comment by Creality-Ralf** [comment]
Yes, it will be supported in the latest update
