### ISSUE TITLE
Customizations for fluidd_pad display

### ISSUE THREAD

**Issue by smwoodward** [CrealityOfficial/Creality_Sonic_Pad#7]
I'm assuming that what is displayed on the sonic pad is based off of KlipperScreen, but i would like to be able to customize what's on the screen some.  Additionally being able to update klipper, mainsail, and fluidd at a faster pace then when updates are released from Creality.  can we get the root credentials to use for customization?

**Comment by marcribe** [comment]
Yes, please!

**Comment by Creality-Ralf** [comment]
The sonic pad ui is not based on the klipper screen, they are completely different things. If you have a UI request, you can ask for it in the "pull requests" section

**Comment by marcribe** [comment]
the visual is exactly the same... including the colors, icons, panels, functions...

**Comment by Creality-Ralf** [comment]
I will close this issue and it looks like it has been resolved
